### ISSUE TITLE
I can not get the right Cider score in the EvalAI

### ISSUE THREAD

**Issue by leonodelee** [wzk1015/CNMT#2]
I use your bash eval_val.sh and get the validation prediction, I submit it to the challenge but get the "CIDEr": 82.9。
I use your bash eval_test.sh and get the test prediction, I submit it to the challenge but get the "CIDEr": 76.54。
I wonder how can I get the right prediction?

**Comment by wzk1015** [comment]
I just submitted to EvalAi server and the result is right (93.03 on test set)
Are you using the correct pretrained checkpoint? Check `--resume_file` in `eval_val.sh`
Also make sure you are submitting to the correct server `https://eval.ai/web/challenges/challenge-page/906/overview` and correct phase

**Comment by leonodelee** [comment]
> I just submitted to EvalAi server and the result is right (93.03 on test set) Are you using the correct pretrained checkpoint? Check `--resume_file` in `eval_val.sh` Also make sure you are submitting to the correct server `https://eval.ai/web/challenges/challenge-page/906/overview` and correct phase

I check the point you said and there seem no wong, I also repeat the same work after re-download your best-checkpoint, but got the same error

**Comment by leonodelee** [comment]
[{"val": {"B4": 20.46, "METEOR": 20.89, "ROUGE-L": 43.15, "SPICE": 14.29, "CIDEr": 82.9}}]
[{"test-standard": {"B4": 17.32, "METEOR": 19.21, "ROUGE-L": 41.62, "SPICE": 12.21, "CIDEr": 76.54}}]
