### ISSUE TITLE
urllib3 botocore requests版本不匹配问题。

### ISSUE THREAD

**Issue by lxq0204** [wzk1015/CNMT#5]
作者您好，在按照requirments.txt文件安装时，总是提示requests==2.21.0版本与urllib3 botocore版本不匹配问题。请问这三者的版本分别是多少？python使用的是哪个版本？

**Comment by wzk1015** [comment]
我这里是Python3.7.7，三个库的版本：

```python
>>> import urllib3
>>> urllib3.__version__
'1.24.3'
>>> import botocore
>>> botocore.__version__
'1.16.6'
>>> import requests
>>> requests.__version__
'2.21.0'

```

可以尝试按这个版本配置一下
（我猜测把requirements.txt里这三个库的版本限制删除（例如`requests==2.21.0`改成`requests`）应该也可以跑通代码
