### ISSUE TITLE
What's the meaning of UNK_IDX?

### ISSUE THREAD

**Issue by leonodelee** [wzk1015/CNMT#6]
self.ocr_to_vocab = torch.ones((num_samples,50), device=torch.device("cuda"), dtype=torch.int64) * self.answer_processor.UNK_IDX
fwd_results["scores"][..., self.answer_processor.UNK_IDX] = -1e10

I cannot find it in your config file and search nothing on the Internet

**Comment by wzk1015** [comment]
`UNK_IDX` is defined in [here](https://github.com/wzk1015/CNMT/blob/3ea062fc1f9d1f9775e809237f203fee4813f24e/pythia/datasets/processors.py#L999), which refers to [this](https://github.com/wzk1015/CNMT/blob/3ea062fc1f9d1f9775e809237f203fee4813f24e/pythia/utils/text_utils.py#L121-L123). In short, it is the index of `<unk>` in the [vocab file](https://github.com/wzk1015/CNMT/blob/master/data/vocab_textcap_threshold_10.txt)
